include Makefile.preprod
include Makefile.prod
include Makefile.dev

.PHONY: help

help:
	@printf "Targets:\n"
	@printf "  dev-webapp-localhost        Lancer le dev Nuxt HMR dans Docker\n"
	@printf "  dev-webapp-ssr              Lancer le SSR via Nginx en mode prod-like\n"
	@printf "  dev-webapp-ssr BUILD=1      Forcer le rebuild du SSR avant lancement\n"
	@printf "  dev-nginx                   Lancer le vhost Nginx SSR\n"
	@printf "  dev-build                   Builder les images Docker dev\n"
	@printf "  dev-build-no-cache          Builder les images Docker dev sans cache\n"
	@printf "  dev-build NO_CACHE=1        Variante sans cache de dev-build\n"
	@printf "  dev-down                    Stopper les containers Docker dev\n"
	@printf "  dev-logs                    Suivre les logs Docker dev\n"
	@printf "  dev-analyze                 Analyser le bundle Nuxt\n"
	@printf "  dev-analyse                 Alias francise de dev-analyze\n"
	@printf "  dev-shell-webapp-localhost  Ouvrir un shell dans le container dev\n"
	@printf "  dev-shell-webapp-ssr        Ouvrir un shell dans le container SSR dev\n"
	@printf "  dev-shell-nginx             Ouvrir un shell dans le container Nginx dev\n"
	@printf "  content-sync                Synchroniser le contenu DEV depuis l'API Symfony\n"
	@printf "  content-sync-dry            Simuler la sync DEV sans écrire sur le disque\n"
	@printf "  generate-schemas            Générer les interfaces TS depuis les schémas YAML\n"
	@printf "  conventions-check           Vérifier les conventions de code\n"
	@printf "  quality-check               Lancer lint + format + type-check\n"
	@printf "  lint-check                  Lancer ESLint\n"
	@printf "  lint-fix                    Corriger ESLint quand possible\n"
	@printf "  format-check                Lancer Prettier\n"
	@printf "  type-check                  Lancer vue-tsc\n"
	@printf "  preprod-content-sync        Synchroniser le contenu PREPROD depuis l'API Symfony\n"
	@printf "  preprod-content-sync-dry    Simuler la sync PREPROD\n"
	@printf "  preprod-up                  Lancer les services preprod\n"
	@printf "  preprod-up-build            Lancer les services preprod avec build\n"
	@printf "  preprod-build               Builder les images preprod\n"
	@printf "  preprod-build-no-cache      Builder les images preprod sans cache\n"
	@printf "  preprod-deploy              Sync + build sans cache + lancement preprod\n"
	@printf "  preprod-down                Stopper les containers preprod\n"
	@printf "  preprod-logs                Suivre les logs preprod\n"
	@printf "  prod-content-sync           Synchroniser le contenu PROD depuis l'API Symfony\n"
	@printf "  prod-content-sync-dry       Simuler la sync PROD\n"
	@printf "  prod-up                     Lancer les services prod\n"
	@printf "  prod-up-build               Lancer la prod avec rebuild\n"
	@printf "  prod-build                  Builder les images prod\n"
	@printf "  prod-build-no-cache         Builder la prod sans cache\n"
	@printf "  prod-deploy                 Sync + build + lancement prod\n"
	@printf "  prod-deploy-no-cache        Sync + build sans cache + lancement prod\n"
	@printf "  prod-down                   Stopper les containers prod\n"
	@printf "  prod-logs                   Suivre les logs prod\n"
