components:
  socialNetwork:
    closeMenuAriaLabel: Cerrar redes sociales
    navAriaLabel: Redes sociales
    openMenuAriaLabel: Abrir redes sociales

accommodation:
  labels:
    bathrooms: Banos
    bedrooms: Dormitorios
    garages: Garajes
    price: Precio
    propertyReference: Referencia
    propertyStatus: Estado del bien
    propertyType: Tipo de bien
    rooms: Estancias
    surface: Superficie
    surfaceHabitable: Superficie habitable
    surfaceTerrain: Superficie del terreno
  sections:
    details: Detalles
    detailsSummary: Resumen de detalles
    location: Ubicacion
    review: Nuestra opinion
    visitGuide: Visita guiada / Descripcion
    wellness: Elementos de confort
  texts:
    noImageAvailable: No hay imagen disponible
    propertyVisual: Visual del bien

navigation:
  agency:
    name: Sobre nosotros / Agencia
    url: /a-propos
  contact:
    name: Contacto
    url: /contact
  fees:
    name: Honorarios
    url: /honoraires
  for-sale:
    name: Propiedades en venta
    url: /properties/bien-a-vendre
  home-staging:
    name: Home Staging
    url: /home-staging
  investing:
    name: Tasación
    url: /estimation
  things-to-do:
    name: Qué hacer en Essaouira
    url: /que-faire-a-essaouira
  legal-notice:
    name: Aviso legal
    url: /mentions-legales
  professionals:
    name: Profesionales
    url: /professionnels
  rental-management:
    name: Gestión de alquiler
    url: /gestion-locative
  seasonal-rental:
    name: Alquileres vacacionales
    url: /properties/location-saisonniere
