components:
  langSwitcher:
    navAriaLabel: Switch language
  logo:
    ariaLabel: Showcase Immobilier
  navigationMain:
    closeMenuAriaLabel: Close menu
    contactDetailsTitle: Contact details
    mainMenuAriaLabel: Main menu
    stayConnectedTitle: Stay connected
  socialNetwork:
    closeMenuAriaLabel: Close social networks
    navAriaLabel: Social networks
    openMenuAriaLabel: Open social networks

footer:
  accommodationTypes:
    label: Property types
    menu: accommodationTypes
  credits: '© 2026 Showcase Immobilier'
  meta:
    label: Information
    menu: meta
  services:
    label: Services
    menu: services
  showColorModeToggle: false
  socialLinks: []

navigation:
  agency:
    name: The agency
    url: /l-agence
  apartment:
    name: Apartment
    url: /biens/appartement
  commercial-business:
    name: Commercial business
    url: /biens/affaires-commerciales
  commercial-property:
    name: Commercial premises
    url: /biens/local-commercial
  contact:
    name: Contact
    url: /contact
    label: Contact us
  country-house:
    name: Country house
    url: /biens/maison-de-campagne
  dar:
    name: Dar
    url: /biens/dar
  essaouira-the-jewel:
    name: Essaouira the authentic jewel
    url: /essaouira-le-joyau-authentique
  fees:
    name: Fees
    url: /honoraires
  for-sale:
    description: A selection of exceptional riads and houses to acquire, nestled between palm groves and medinas.
    imageIdentifier: /demo/coast.svg
    name: Properties for Sale
    url: /properties/bien-a-vendre
  golf-villa:
    name: Golf villa
    url: /biens/villa-golf
  guest-house:
    name: Guest house
    url: /biens/maisons-dhotes
  guest-room:
    name: Guest room
    url: /biens/chambre-dhotes
  home-staging:
    name: Home Staging
    url: /home-staging
  investing:
    name: Invest
    url: /investir
    label: More info
  land:
    name: Land
    url: /biens/terrain
  lease-management:
    name: Lease management
    url: /biens/location-gerance
  legal-notice:
    name: Legal notice
    url: /mentions-legales
  partnerships:
    name: Partenariats
    url: /partnerships
  long-term-rental:
    description: An offer dedicated to hoteliers, brands and events seeking sensory settings.
    imageIdentifier: /demo/coast.svg
    name: Long-term rentals
    url: /properties/location-longue-duree
  rental-management:
    name: Rental management
    url: /gestion-locative
  riad:
    name: Riad
    url: /biens/riad
  seasonal-rental:
    description: Villas, patios and kasbahs available for stays, designed for luminous experiences.
    imageIdentifier: /demo/coast.svg
    name: Seasonal rentals
    url: /properties/location-saisonniere
  town-house:
    name: Town house
    url: /biens/maison-de-ville
