export type ResourceKey =
  | 'app'
  | 'web-pages'
  | 'articles'
  | 'travels'
  | 'real-estate-listing'
  | 'accommodation-category'
  | 'category-code'
  | 'accommodation-place'
  | 'media-object'
  | 'accommodations'
  | 'forms/accommodation'
  | 'dashboard'
  | 'ui/accommodation'
