components:
  socialNetwork:
    closeMenuAriaLabel: Close social networks
    navAriaLabel: Social networks
    openMenuAriaLabel: Open social networks

accommodation:
  labels:
    bathrooms: Bathrooms
    bedrooms: Bedrooms
    garages: Garages
    price: Price
    propertyReference: Reference
    propertyStatus: Property status
    propertyType: Property type
    rooms: Rooms
    surface: Surface
    surfaceHabitable: Living area
    surfaceTerrain: Land area
  sections:
    details: Details
    detailsSummary: Summary details
    location: Location
    review: Our view
    visitGuide: Guided tour / Description
    wellness: Comfort features
  texts:
    noImageAvailable: No image available
    propertyVisual: Property visual

navigation:
  agency:
    name: About / Agency
    url: /a-propos
  contact:
    name: Contact
    url: /contact
  fees:
    name: Fees
    url: /honoraires
  for-sale:
    name: Properties for Sale
    url: /properties/bien-a-vendre
  home-staging:
    name: Home Staging
    url: /home-staging
  investing:
    name: Valuation
    url: /estimation
  things-to-do:
    name: What to do in Essaouira
    url: /que-faire-a-essaouira
  legal-notice:
    name: Legal Notice
    url: /mentions-legales
  professionals:
    name: Professionals
    url: /professionnels
  rental-management:
    name: Rental Management
    url: /gestion-locative
  seasonal-rental:
    name: Holiday Rentals
    url: /location-saisonniere
