name: conventions

on:
  pull_request:
  push:
    branches: [develop, main]

jobs:
  conventions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.22
      - run: bun install
      - run: bun run check:app:types
      - run: bun run check:app:images
      - run: bun run check:app:components:no-business-logic
      - run: bun run check:app:script-setup-standard
      - run: bun run check:app:soc
      - run: bun run check:app:code-quality
      - run: bun run check:app:solid
      - run: bun run check:services:no-framework-imports
